package dev.pocketopencode

import java.util.Locale

/** Shared catalog for native views, Compose, notifications and runtime messages.
 * Keep placeholders identical in every translation. Tool/model output is not translated.
 */
enum class UiText(val en: String, val ru: String) {
    Stopped("Stopped", "Остановлен"),
    MissingCore("This APK has no ARM64 core. Install the full arm64-v8a build.", "В APK нет ARM64-ядра. Нужна полная сборка для arm64-v8a."),
    LinkFailed("Could not update link %1\$s", "Не удалось обновить ссылку %1\$s"),
    ConnectingTermux("Connecting to Termux…", "Подключение Termux…"),
    Preparing("Preparing environment…", "Подготовка среды…"),
    Starting("Starting OpenCode…", "Запуск OpenCode…"),
    LogError("Log: %1\$s", "Журнал: %1\$s"),
    CoreExitDetails("OpenCode exited with code %1\$s. See Runtime for details.", "OpenCode завершился с кодом %1\$s. Подробности во вкладке «Среда»."),
    CoreTimeout("OpenCode did not respond within 90 seconds. Open the environment log.", "OpenCode не ответил за 90 секунд. Откройте журнал среды."),
    EmbeddedStatus("OpenCode · embedded", "OpenCode · встроенная среда"),
    CoreExited("Core exited: %1\$s", "Ядро завершилось: %1\$s"),
    StartFailed("Startup failed", "Ошибка запуска"),
    TermuxMissingMode("Termux is not installed. Select automatic mode or the embedded environment.", "Termux не установлен. Выберите автоматический режим или встроенную среду."),
    TermuxUnsupportedMode("This Termux version does not support the connection. Open Runtime: a GitHub or F-Droid build is required.", "Эта версия Termux не поддерживает подключение. Откройте «Среда»: нужна сборка из GitHub или F-Droid."),
    ConnectTermuxHint("Connect Termux: tap Runtime → Allow and connect.", "Подключите Termux: нажмите «Среда» → «Разрешить и подключить»."),
    TermuxLaunchEnded("Termux launch ended: %1\$s", "Termux завершил запуск: %1\$s"),
    TermuxRuntimeLog("The core, files and commands run in Termux. HOME=%1\$s", "Ядро, файлы и команды работают в Termux. HOME=%1\$s"),
    TermuxCoreExited("OpenCode in Termux exited. %1\$s", "OpenCode в Termux завершился. %1\$s"),
    PortRange("Port must be between 1024 and 65535", "Порт должен быть от 1024 до 65535"),
    StopEmbeddedFirst("Stop the embedded core first", "Сначала остановите встроенное ядро"),
    TermuxNotResponding("OpenCode in Termux is not responding", "OpenCode в Termux не отвечает"),
    EmbeddedCommandsDisabled("Termux is selected. Embedded commands are disabled.", "Выбрана среда Termux. Встроенные команды отключены."),
    CommandTimeout("Command exceeded the %1\$s-second limit", "Команда превысила лимит %1\$s секунд"),
    ExitCode("Exit code %1\$s", "Код выхода %1\$s"),
    LocalOpenCode("Local OpenCode", "Локальный OpenCode"),
    EnvironmentRunning("Local environment is running", "Локальная среда запущена"),
    Stop("Stop", "Остановить"),
    PermissionSettingsHint("Allow running commands in Termux in the app's additional permissions.", "Разрешите «Выполнение команд в Termux» в дополнительных разрешениях приложения."),
    EnvironmentTitle("OpenCode environment", "Среда OpenCode"),
    AutomaticHelp("Automatic: when Termux is installed, the core and all tools run there. Otherwise, the embedded environment is used. Connection errors do not switch the environment automatically.", "Автоматически: если есть Termux — ядро и все инструменты работают в нём. Без Termux используется встроенная среда. При ошибке подключения среда сама не меняется."),
    AutomaticMode("Automatic (prefer Termux)", "Автоматически (приоритет Termux)"),
    TermuxOnly("Termux only", "Только Termux"),
    EmbeddedMode("Embedded environment", "Встроенная среда"),
    TermuxFirstConnection("First Termux connection", "Первое подключение Termux"),
    TermuxUnsupportedBackup("The installed build does not support RUN_COMMAND. Use Termux from GitHub or F-Droid. Back up Termux files before replacing it.", "Установленная сборка не поддерживает RUN_COMMAND. Нужен Termux из GitHub или F-Droid. Перед заменой сохраните файлы Termux."),
    TermuxReleases("Official Termux releases", "Официальные сборки Termux"),
    TermuxSteps("1. Open Termux at least once.\n2. Copy the command below and run it in Termux.\n3. Return and tap Allow and connect.", "1. Откройте Termux хотя бы один раз.\n2. Скопируйте команду ниже и выполните её в Termux.\n3. Вернитесь и нажмите «Разрешить и подключить»."),
    TermuxPackagesHelp("The app installs missing Git, Node.js, ripgrep and ZIP tools through the Termux package manager. Initial setup requires internet access and may take several minutes.", "Недостающие Git, Node.js, ripgrep и утилиты ZIP приложение установит само через менеджер пакетов Termux. Первая настройка требует интернета и может занять несколько минут."),
    CopySetup("Copy setup command", "Скопировать команду настройки"),
    TermuxSetup("Termux setup", "Настройка Termux"),
    CommandCopied("Command copied", "Команда скопирована"),
    OpenTermux("Open Termux", "Открыть Termux"),
    TermuxMissing("Termux is not installed", "Termux не установлен"),
    AllowConnect("Allow and connect", "Разрешить и подключить"),
    InstallTermuxFirst("Install Termux first", "Сначала установите Termux"),
    TermuxUnsupported("This Termux build does not support RUN_COMMAND", "Эта сборка Termux не поддерживает подключение RUN_COMMAND"),
    SeparateProjectsHelp("Embedded projects and history are stored separately. Select Embedded environment to return to them. Termux mode uses its folders, OpenCode settings and installed packages.", "Проекты и история встроенной среды сохраняются отдельно. Вернуться к ним можно выбором «Встроенная среда». В режиме Termux используются его папки, настройки OpenCode и установленные пакеты."),
    BackToOpenCode("Back to OpenCode", "Вернуться в OpenCode"),
    TermuxInstalledLine("Termux is installed\n", "Termux установлен\n"),
    TermuxMissingLine("Termux is not installed\n", "Termux не установлен\n"),
    Files("Files", "Файлы"),
    Environment("Runtime", "Среда"),
    Projects("Projects", "Проекты"),
    NewProject("New project", "Новый проект"),
    ImportZip("Import ZIP", "Импорт ZIP"),
    CloneGit("Clone Git repository", "Клонировать Git"),
    ExportZip("Export ZIP", "Экспорт ZIP"),
    OpenProjectBack("← Open project in OpenCode", "← Открыть проект в OpenCode"),
    ImportProject("Import project", "Импорт проекта"),
    GitRepository("Git repository", "Git-репозиторий"),
    NewFile("New file", "Новый файл"),
    FilePathHint("Path, e.g. src/main.js", "Путь, например src/main.js"),
    ProjectName("Project name", "Название проекта"),
    ImportZipHelp("The archive will be extracted into a separate project on this phone.", "Архив будет распакован в отдельный проект на телефоне."),
    ChooseZip("Choose ZIP", "Выбрать ZIP"),
    Create("Create", "Создать"),
    Cancel("Cancel", "Отмена"),
    Close("Close", "Закрыть"),
    CodeOnTheGo("Code on the go", "Код — с собой"),
    StartEmbeddedHelp("Start embedded OpenCode. Projects and commands will run on this device.", "Запустите встроенный OpenCode. Проекты и команды будут работать на этом устройстве."),
    OpenEnvironment("Open environment", "Открыть среду"),
    FirstProject("Your first project", "Первый проект"),
    CreateProjectHelp("Create a folder, import a ZIP or clone a Git repository.", "Создайте папку, импортируйте ZIP или клонируйте Git-репозиторий."),
    CreateProject("Create project", "Создать проект"),
    NewConversation("New conversation", "Новый диалог"),
    ProjectPrompt("What shall we change in %1\$s?", "Что изменим в %1\$s?"),
    AgentHelp("Describe a task. The agent can read code, suggest changes and run commands.", "Опиши задачу. Агент сможет читать код, предлагать изменения и запускать команды."),
    AllowAction("Allow this action?", "Разрешить действие?"),
    Reject("Reject", "Отклонить"),
    AllowOnce("Allow once", "Разрешить один раз"),
    AgentWorking("  OpenCode is working…", "  OpenCode работает…"),
    ChooseModelArrow("Choose a model →", "Выберите модель →"),
    AgentTask("Task for the agent…", "Задача для агента…"),
    StopTask("Stop task", "Остановить задачу"),
    Send("Send", "Отправить"),
    You("YOU", "ВЫ"),
    Reasoning("Reasoning %1\$s", "Размышления %1\$s"),
    AgentQuestion("Question from the agent", "Уточнение от агента"),
    YourAnswer("Your answer", "Ваш ответ"),
    Answer("Answer", "Ответить"),
    TermuxProject("Project in Termux", "Проект в Termux"),
    TermuxFilesHelp("The agent can access this project's files in Termux. The embedded editor works with Opencode projects.", "Файлы этого проекта доступны агенту в Termux. Встроенный редактор работает с проектами Opencode."),
    NoProject("No project", "Нет проекта"),
    ProjectsMenuHelp("Open the Projects menu at the top.", "Откройте меню «Проекты» сверху."),
    Back("Back", "Назад"),
    Save("Save", "Сохранить"),
    EmptyFolder("This folder has no files yet", "В этой папке пока нет файлов"),
    AgentChanges("Agent changes", "Изменения агента"),
    Refresh("Refresh", "Обновить"),
    NoChanges("No changes yet", "Пока без изменений"),
    ChangesHelp("Files changed in the selected conversation will appear here.", "Здесь появятся файлы, изменённые в выбранном диалоге."),
    Before("BEFORE", "ДО"),
    After("AFTER", "ПОСЛЕ"),
    DeviceEnvironment("Environment on this device", "Среда на устройстве"),
    EmbeddedToolsHelp("Bundled core, Git, ripgrep and Node.js. This mode does not require Termux.", "Встроенные ядро, Git, ripgrep и Node.js. Termux для этого режима не нужен."),
    ExperimentalBuild("Experimental build: ARM64 core compatibility is checked at startup.", "Экспериментальная сборка: совместимость ARM64-ядра с устройством проверяется при запуске."),
    Start("Start", "Запустить"),
    ProjectCommand("Command in project", "Команда в проекте"),
    ShellCommand("Shell command", "Команда shell"),
    Run("Run", "Выполнить"),
    NpmHelp("For npm: node \"\$NPM_CLI\" install --ignore-scripts. Run JS files with: node path/to/file.js.", "Для npm: node \"\$NPM_CLI\" install --ignore-scripts. Запуск JS-файлов: node путь/к/файлу.js."),
    CoreLog("Core log", "Журнал ядра"),
    CoreNotStarted("The core has not been started yet.", "Ядро ещё не запускалось."),
    ModelConnection("Model and connection", "Модель и подключение"),
    ProviderListHelp("The provider and model list comes from your OpenCode instance.", "Список провайдеров и моделей приходит из вашего OpenCode."),
    StartCoreFirst("Start the core in the Runtime tab first.", "Сначала запустите ядро во вкладке «Среда»."),
    ProviderApiKey("Provider API key", "API-ключ провайдера"),
    ConnectThroughOpenCode("Connect through OpenCode", "Подключить через OpenCode"),
    KeyStorageHelp("OpenCode saves the key in the app's private directory. App data backups are disabled.", "Ключ сохраняет OpenCode в закрытом каталоге приложения. Резервное копирование данных приложения отключено."),
    ActiveModel("Active model", "Активная модель"),
    ChooseModel("Choose a model", "Выберите модель"),
    ConnectProviderHelp("Connect a provider, then refresh the model list.", "Подключите провайдера, затем обновите список моделей."),
    RefreshList("Refresh list", "Обновить список"),
    AdvancedTermux("Advanced: OpenCode in Termux %1\$s", "Дополнительно: OpenCode в Termux %1\$s"),
    ManualTermuxHelp("Connect only to this phone (127.0.0.1). Run opencode serve in Termux and enter its port, password and project path.", "Подключение только к этому телефону (127.0.0.1). Запустите opencode serve в Termux и укажите его порт, пароль и путь проекта."),
    Port("Port", "Порт"),
    ServerPassword("Server password", "Пароль сервера"),
    TermuxProjectPath("Project path in Termux", "Путь проекта в Termux"),
    Connect("Connect", "Подключиться"),
    About("Opencode · %1\$s\nUnofficial app. The interface uses the OpenCode API.", "Opencode · %1\$s\nНеофициальное приложение. Интерфейс использует API OpenCode."),
    StartOpenCodeFirst("Start OpenCode in the Runtime tab first", "Сначала запустите OpenCode во вкладке «Среда»"),
    TermuxFilesPrivate("Termux files belong to another app. Work with them through the agent.", "Файлы Termux принадлежат другому приложению. Работайте с ними через агента."),
    ChooseProject("Choose a project", "Выберите проект"),
    ProjectExported("Project exported", "Проект экспортирован"),
    UseHttpsGit("Use an HTTPS Git repository URL", "Используйте HTTPS-адрес Git-репозитория"),
    Conversation("Conversation", "Диалог"),
    ChooseProviderModel("Connect a provider and choose a model in settings", "Подключите провайдера и выберите модель в настройках"),
    EnterApiKey("Enter an API key", "Введите API-ключ"),
    ProviderConnected("Provider connected through OpenCode", "Провайдер подключён через OpenCode"),
    ChooseConversation("Choose a conversation", "Выберите диалог"),
    FileSaved("File saved", "Файл сохранён"),
    FileExists("File already exists", "Файл уже существует"),
    AbsoluteTermuxPath("An absolute project path in Termux is required", "Нужен абсолютный путь проекта в Termux"),
    AbsolutePath("An absolute project path is required", "Нужен абсолютный путь проекта"),
    TransferInterrupted("Transfer interrupted", "Передача прервалась"),
    ArchiveNotReceived("Termux did not send the archive", "Termux не передал архив"),
    TermuxEmptyResult("Termux returned an empty result", "Termux вернул пустой результат"),
    TermuxUnsupportedBridge("This Termux build has no RUN_COMMAND connection. Install Termux from GitHub or F-Droid; the Google Play version is not supported.", "В этой сборке Termux нет подключения RUN_COMMAND. Установите Termux из GitHub или F-Droid; версия Google Play не подходит."),
    TermuxPermissionHint("Allow running commands in Termux: Runtime → Allow and connect", "Разрешите выполнение команд в Termux: кнопка «Среда» → «Разрешить и подключить»"),
    TermuxCommandTooLarge("The command is too large for the Termux connection", "Команда слишком большая для подключения Termux"),
    TermuxServiceFailed("Could not start the Termux service", "Не удалось запустить службу Termux"),
    TermuxExitCode("Termux: exit code %1\$s", "Termux: код %1\$s"),
    TermuxConnectionTimeout("Termux did not respond. Check allow-external-apps=true, open Termux and try connecting again.", "Termux не ответил. Проверьте allow-external-apps=true, откройте Termux и повторите подключение."),
    ProjectImportedTermux("Project imported into Termux", "Проект импортирован в Termux"),
    TermuxProjects("Projects · Termux", "Проекты · Termux"),
    TermuxProjectHelp("Files, Git and commands run in Termux. Open existing Termux folders using the project picker in OpenCode.", "Файлы, Git и команды выполняются в Termux. Его существующие папки можно открыть через выбор проекта в OpenCode."),
    OpenInOpenCode("Open in OpenCode", "Открыть в OpenCode"),
    TermuxProjectFolder("Project folder in Termux", "Папка проекта в Termux"),
    NewProjectName("New project name", "Название нового проекта"),
    OptionalGitUrl("HTTPS Git URL (optional)", "HTTPS Git URL (необязательно)"),
    InvalidProjectName("Invalid project name", "Недопустимое название проекта"),
    HttpsRepositoryRequired("An HTTPS repository URL is required", "Нужен HTTPS-адрес репозитория"),
    CreateInTermux("Create in Termux", "Создать в Termux"),
    CloneInTermux("Clone in Termux", "Клонировать в Termux"),
    ImportIntoTermux("Import ZIP into Termux", "Импорт ZIP в Termux"),
    ExportSelectedProject("Export selected project", "Экспорт выбранного проекта"),
    CopyEmbeddedProject("Copy a project from the embedded environment", "Скопировать проект из встроенной среды"),
    CopyProjectHelp("Only files are copied. Chat history stays in the embedded environment. An existing Termux folder with the same name will not be overwritten.", "Копируются файлы. История чатов остаётся во встроенной среде. Если папка с таким именем уже есть в Termux, она не перезаписывается."),
    TermuxCommand("Command in Termux", "Команда в Termux"),
    EnvironmentOldProjects("Environment settings / previous projects", "Настройка среды / старые проекты"),
    InvalidTransferSize("Invalid transfer size", "Недопустимый размер передачи"),
    UnexpectedTermuxResponse("Unexpected Termux response: %1\$s", "Неожиданный ответ Termux: %1\$s"),
    InstallingTermuxTools("Installing tools in Termux…", "Установка инструментов в Termux…"),
    StartingTermux("Starting OpenCode in Termux…", "Запуск OpenCode в Termux…"),
    Chat("+ Chat", "+ Чат"),
    NewChat("New chat", "Новый чат"),
    NewChatTooltip("New session in the current project", "Новая сессия в текущем проекте"),
    WebError("Interface error: %1\$s", "Ошибка интерфейса: %1\$s"),
    ChooseProjectHelp("Open or create a project first. Then + Chat will create a new session in it.", "Сначала откройте или создайте проект. После этого «+ Чат» создаст в нём новую сессию."),
    NewChatFailed("Could not create chat: %1\$s", "Не удалось создать чат: %1\$s"),
    OpenProjectFailed("Could not open project: %1\$s", "Не удалось открыть проект: %1\$s"),
    ProjectNameRules("Name: 1–64 letters, numbers, spaces or hyphens", "Название: 1–64 буквы, цифры, пробелы или дефисы"),
    ProjectExists("Project already exists", "Проект уже существует"),
    CreateProjectFailed("Could not create project", "Не удалось создать проект"),
    InvalidPath("Invalid path", "Недопустимый путь"),
    OutsideWorkspace("Folder is outside the workspace", "Папка вне рабочего каталога"),
    OutsideProject("Path is outside the project", "Путь выходит за пределы проекта"),
    TooManyFiles("The archive has too many files", "В архиве слишком много файлов"),
    ArchiveTooLarge("The extracted archive exceeds 256 MB", "Распакованный архив больше 256 МБ"),
    EditorSizeLimit("The editor opens files up to 1 MB", "Редактор открывает файлы до 1 МБ"),
    BinaryFile("This is a binary file", "Это двоичный файл"),
    InstallZip("Install zip: pkg install zip", "Установите zip: pkg install zip"),
    LanguageHelp("The Android interface follows the OpenCode language setting. Russian and English are available; other languages use English.", "Язык Android-части следует настройке языка OpenCode. Доступны русский и английский; для остальных языков используется английский."),
    CopyDiagnostics("Copy startup diagnostics", "Скопировать диагностику запуска"),
    Updates("Updates", "Обновления"),
    AutomaticUpdates("Check automatically once a day", "Проверять автоматически раз в сутки"),
    CheckUpdates("Check for updates", "Проверить обновления"),
    CheckingUpdates("Checking GitHub Releases…", "Проверяем GitHub Releases…"),
    UpToDate("You have the latest available version.", "У вас последняя доступная версия."),
    UpdateAvailable("Opencode %1\$s is available", "Доступна версия Opencode %1\$s"),
    UpdateInstallHelp("Download the APK and install it over the current app to keep your data.", "Скачайте APK и установите поверх текущего приложения, чтобы сохранить данные."),
    DownloadApk("Download APK", "Скачать APK"),
    CancelUpdate("Cancel download", "Отменить загрузку"),
    RetryUpdate("Download again", "Скачать заново"),
    InstallUpdate("Install update", "Установить обновление"),
    UpdateReady("100%% · Download complete. Ready to install.", "100%% · Загрузка завершена. Можно устанавливать."),
    UpdateWaiting("Waiting for download or network…", "Ожидание загрузки или сети…"),
    UpdateDownloadFailed("Download failed. Check your connection and available storage, then retry.", "Не удалось скачать. Проверьте подключение и свободное место, затем повторите."),
    VerifyingUpdate("Verifying update…", "Проверяем обновление…"),
    UpdateInstallFailed("Could not verify or open the update. Download it again and retry.", "Не удалось проверить или открыть обновление. Скачайте его заново и повторите."),
    UpdateLater("Later", "Позже"),
    UpdateCheckFailed("Could not check for updates. Check your connection and try again later.", "Не удалось проверить обновления. Проверьте подключение и повторите позже."),
    DiagnosticsCopied("Diagnostics copied. Review before sharing.", "Диагностика скопирована. Проверьте перед отправкой."),
    TermuxStatus("OpenCode · Termux", "OpenCode · Termux"),
    PhoneControlTitle("Phone control", "Управление телефоном"),
    PhoneControlOn("On: the agent can read the screen, tap, type and open apps. Actions follow your OpenCode permission settings.", "Включено: агент видит экран, нажимает, вводит текст и открывает приложения. Действия подчиняются настройкам разрешений OpenCode."),
    PhoneControlOff("Off. Turn on “Opencode phone control” in Accessibility settings.", "Выключено. Включите «Opencode: управление телефоном» в настройках специальных возможностей."),
    PhoneControlHelp("If Android says the setting is restricted: App info → ⋮ → Allow restricted settings, then try again.", "Если Android пишет, что настройка ограничена: «О приложении» → ⋮ → «Разрешить ограниченные настройки», затем повторите."),
    PhoneControlSettings("Open accessibility settings", "Открыть специальные возможности");

    fun format(locale: String, vararg args: Any?): String =
        String.format(Locale.ROOT, if (nativeLanguage(locale) == "ru") ru else en, *args)
}

fun nativeLanguage(locale: String): String = if (locale.substringBefore('-').substringBefore('_').equals("ru", true)) "ru" else "en"

fun tr(key: UiText, vararg args: Any?): String = key.format(NativeLanguage.locale.value, *args)
